In [40]:
import pandas as pd
import numpy as np

df = pd.read_csv("rentals.csv")

area = df["area"]
rent_amount = df["rent amount (R$)"]
fire_insurance = df["fire insurance (R$)"]

mean_area = np.mean(area)
mean_rent_amount = np.mean(rent_amount)
mean_fire_insurance = np.mean(fire_insurance)
df.head()


def custom_cov(n1, n2):
    n1_mean = np.mean(n1)
    n2_mean = np.mean(n2)
    start = 0
    total = 0
    
    while start < len(n1):
        total += (n1[start] - n1_mean) * (n2[start] - n2_mean)
        start += 1
        
    return total / (len(n1) - 1) # Subtracting 1 matches up to np variance function 

print("my covariance function :", custom_cov(area, area))
print("np covariance function:", np.cov(area))
print("np variance function:", np.var(area)) # A little of, however if I take out subtracting one for the run then matches
    
# Get a column of data
column = df[["area", "fire insurance (R$)", "rent amount (R$)"]]

my covariance function : 288360.2241158425
np covariance function: 288387.196356425
np variance function: 288360.2241158425
my covariance funtion test 2 116.88
matches


In [28]:
def cov_matrix_calculation(data):
    # calculate covariance matrix of the data
    cov_matx = np.cov(data, rowvar=False) # or can just use data.T as input
    return cov_matx

dataset = np.array([[1, 1, 1], [1, 2, 1], [1, 3, 2], [1, 4, 3]])
print(cov_matrix_calculation(dataset))
print("\n matrix for my rental property data")
print(cov_matrix_calculation(colum))

[[0.         0.         0.        ]
 [0.         1.66666667 1.16666667]
 [0.         1.16666667 0.91666667]]

 matrix for my rental property data
[[2.88387196e+05 4.82462370e+03 3.30839201e+05]
 [4.82462370e+03 2.28178478e+03 1.60758731e+05]
 [3.30839201e+05 1.60758731e+05 1.16181825e+07]]
